version: '3.1'

services:
  node-docker:
    build:
      context: .
      dockerfile: node-back/Dockerfile
      target: base
    volumes:
      - ./node-back/src:/home/node/app/src
      # - ./nodemon.json:/home/node/app/nodemon.json
    container_name: node-docker
    expose:
      - '8081'
    ports:
      - '8081:8081'
    command: npm start
  
  front-docker:
    build:
      context: .
      dockerfile: express_app/Dockerfile
      target: base
    volumes:
      - ./express_app/src:/home/node/front/src
      # - ./nodemon.json:/home/node/app/nodemon.json
    container_name: front-docker
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: npm start

